### ISSUE TITLE
mediation_path_diagram.m function stopped working properly in Matlab 2014b

### ISSUE THREAD

**Issue by ljchang** [canlab/MediationToolbox#1]
![2015-03-02_08-27-07](https://cloud.githubusercontent.com/assets/2993338/6443710/fdd6879c-c0b5-11e4-8eec-39d8a770ec56.png)
![2015-03-02_08-27-26](https://cloud.githubusercontent.com/assets/2993338/6443713/004922d2-c0b6-11e4-977c-d61f7796ca30.png)

**Comment by mariannnne** [comment]
Not a solution, but...
mediation_path uses this external toolbox http://www.mathworks.com/matlabcentral/fileexchange/7844-geom2d
we should track and see if they update for the new plotting structure

**Comment by ljchang** [comment]
Good point.  That package could be the culprit, thanks.

**Comment by sgeuter** [comment]
should be working again. updated the arrow.m function and geo2d had been updated, too, by somebody
