### ISSUE TITLE
problems running mediation.m

### ISSUE THREAD

**Issue by charujing** [canlab/MediationToolbox#22]
Dear professors and users,
I am trying to plot the mediation results using [paths, stats2] =mediation(x(:,1),x(:,j),x(:,i), 'plots',  'boottop').
However, it echos errors about the "create_figure" was not found. It could report results when remove the option "plots".
Could anyone help me fix this?
Thanks.
rujing

**Comment by torwager** [comment]
Hi Rujing,

This means that you need the “CANlab Core Tools” repository on your path.  create_figure is there.

Best,
Tor

**Comment by charujing** [comment]
Dear Tor
      It's working. Thanks very much for your helpful and fast reply.
      All the best.
rujing
